package com.ssakura49.sakuratinker.register;

import com.ssakura49.sakuratinker.SakuraTinker;
import com.ssakura49.sakuratinker.content.tinkering.modifiers.armor.*;
import com.ssakura49.sakuratinker.content.tinkering.modifiers.curio.*;
import com.ssakura49.sakuratinker.content.tinkering.modifiers.misc.*;
import com.ssakura49.sakuratinker.content.tinkering.modifiers.melee.*;
import com.ssakura49.sakuratinker.compat.EnigmaticLegacy.spellstone.GolemHeartModifier;
import com.ssakura49.sakuratinker.content.tinkering.modifiers.special.*;
import com.ssakura49.sakuratinker.content.tinkering.modifiers.mining.BedrockBreakerModifier;
import slimeknights.tconstruct.library.modifiers.util.ModifierDeferredRegister;
import slimeknights.tconstruct.library.modifiers.util.StaticModifier;

public class STModifiers {
    public static ModifierDeferredRegister MODIFIERS = ModifierDeferredRegister.create(SakuraTinker.MODID);

    public static StaticModifier<SolidModifier> Solid;
    public static StaticModifier<VoidModifier> Void;
    public static StaticModifier<WitherSymbiosisModifier> Wither_Symbiosis;
    public static StaticModifier<CelestialModifier> Celestial;
    public static StaticModifier<RuinationModifier> Ruination;
    public static StaticModifier<EternityModifier> Eternity;
    public static StaticModifier<NullAlmightyModifier> Null_Almighty;
    public static StaticModifier<MortalWoundModifier> Mortal_Wound;
    public static StaticModifier<KoboldModifier> Kobold;
    public static StaticModifier<StormVeilModifier> Storm_Veil;
    public static StaticModifier<RootednessModifier> Rootedness;
    public static StaticModifier<NetherGhostModifier> Nether_Ghost;
    public static StaticModifier<GaleModifier> Gale;
    public static StaticModifier<EvilEyeModifier> Evil_Eye;
    public static StaticModifier<OmnipotenceModifier> Omnipotence;
    public static StaticModifier<GuardianShellModifier> GuardianShell;
    public static StaticModifier<BodyImpactModifier> BodyImpact;
    public static StaticModifier<SpectralModifier> Spectral;
    public static StaticModifier<HardenedSkinModifier> HardenedSkin;
    public static StaticModifier<DisslovingModifier> Dissloving;
    public static StaticModifier<GreedyModifier> Greedy;
    public static StaticModifier<EnergyInfusionModifier> EnergyInfusion;
    public static StaticModifier<SoulSiphonModifier> SoulSiphon;
    public static StaticModifier<InfinitumModifier> Infinitum;
    public static StaticModifier<PainResonanceModifier> PainResonance;
    public static StaticModifier<NeutronCondenseModifier> NeutronCondense;
    public static StaticModifier<AbsorptionModifier> Absorption;
    public static StaticModifier<JinxDollModifier> JinxDoll;
    public static StaticModifier<ColorizationModifier> Colorization;
    public static StaticModifier<HeavyModifier> Heavy;
    public static StaticModifier<SwiftSwordTechniqueModifier> SwiftSwordTechnique;
    public static StaticModifier<SoulBoundCurioModifier> SoulBoundCurio;
    public static StaticModifier<MambaModifier> Mamba;
    public static StaticModifier<DwarvenCurioModifier> DwarvenCurio;
    public static StaticModifier<LaceratingCurioModifier> LaceratingCurio;
    public static StaticModifier<MagneticCurioModifier> MagneticCurio;
    public static StaticModifier<LightWeightCurioModifier> LightWeightCurio;
    public static StaticModifier<WorldBottomModifier> WorldBottom;
    public static StaticModifier<HighFrequencyBarrierModifier> HighFrequencyBarrier;
    public static StaticModifier<BladeConvergenceModifier> BladeConvergence;
    public static StaticModifier<TorturingModifier> Torturing;
    public static StaticModifier<CrystallineModifier> Crystalline;
    public static StaticModifier<CrystallineArmorModifier> CrystallineArmor;
    public static StaticModifier<ReapersBlessingModifier> ReapersBlessing;
    public static StaticModifier<BedrockBreakerModifier> BedrockBreaker;
    public static StaticModifier<BatteryCell> BatteryCell;
    public static StaticModifier<ThunderModifier> Thunder;
    public static StaticModifier<FieryFireModifier> FieryFire;
    public static StaticModifier<FrozenModifier> Frozen;
    public static StaticModifier<FireImmunityModifier> FireImmunity;
    public static StaticModifier<IceImmunityModifier> IceImmunity;
    public static StaticModifier<LightningImmunityModifier> LightningImmunity;
    public static StaticModifier<ChainLightningModifier> ChainLightning;
    public static StaticModifier<DragonSoulModifier> DragonSoul;
    public static StaticModifier<SoulDevourerModifier> SoulDevourer;
    public static StaticModifier<ShieldingModifier> Shielding;
    public static StaticModifier<SteadyCurioModifier> SteadyCurio;
    public static StaticModifier<InsatiableCurioModifier> InsatiableCurio;

    static {
        Solid = MODIFIERS.register("solid", SolidModifier::new);
        Void = MODIFIERS.register("void", VoidModifier::new);
        Wither_Symbiosis = MODIFIERS.register("wither_symbiosis", WitherSymbiosisModifier::new);
        Celestial = MODIFIERS.register("celestial", CelestialModifier::new);
        Ruination = MODIFIERS.register("ruination", RuinationModifier::new);
        Eternity = MODIFIERS.register("eternity", EternityModifier::new);
        Null_Almighty = MODIFIERS.register("null_almighty", NullAlmightyModifier::new);
        Mortal_Wound = MODIFIERS.register("mortal_wound", MortalWoundModifier::new);
        Kobold = MODIFIERS.register("kobold", KoboldModifier::new);
        Storm_Veil = MODIFIERS.register("storm_veil", StormVeilModifier::new);
        Rootedness = MODIFIERS.register("rootedness", RootednessModifier::new);
        Nether_Ghost = MODIFIERS.register("nether_ghost", NetherGhostModifier::new);
        Gale = MODIFIERS.register("gale", GaleModifier::new);
        Evil_Eye = MODIFIERS.register("evil_eye", EvilEyeModifier::new);
        Omnipotence = MODIFIERS.register("omnipotence", OmnipotenceModifier::new);
        GuardianShell = MODIFIERS.register("guardian_shell", GuardianShellModifier::new);
        BodyImpact = MODIFIERS.register("body_impact", BodyImpactModifier::new);
        Spectral = MODIFIERS.register("spectral", SpectralModifier::new);
        HardenedSkin = MODIFIERS.register("hardened_skin", HardenedSkinModifier::new);
        Dissloving = MODIFIERS.register("dissloving", DisslovingModifier::new);
        Greedy = MODIFIERS.register("greedy", GreedyModifier::new);
        EnergyInfusion = MODIFIERS.register("energy_infusion", EnergyInfusionModifier::new);
        SoulSiphon = MODIFIERS.register("soul_siphon", SoulSiphonModifier::new);
        Infinitum = MODIFIERS.register("infinitum", InfinitumModifier::new);
        PainResonance = MODIFIERS.register("pain_resonance", PainResonanceModifier::new);
        NeutronCondense = MODIFIERS.register("neutron_condense", NeutronCondenseModifier::new);
        Absorption = MODIFIERS.register("absorption", AbsorptionModifier::new);
        JinxDoll =MODIFIERS.register("jinx_doll", JinxDollModifier::new);
        Colorization = MODIFIERS.register("colorization", ColorizationModifier::new);
        Heavy = MODIFIERS.register("heavy", HeavyModifier::new);
        SwiftSwordTechnique = MODIFIERS.register("swift_sword_technique", SwiftSwordTechniqueModifier::new);
        SoulBoundCurio = MODIFIERS.register("soul_bound_curio", SoulBoundCurioModifier::new);
        Mamba = MODIFIERS.register("mamba", MambaModifier::new);
        DwarvenCurio = MODIFIERS.register("dwarven_curio", DwarvenCurioModifier::new);
        LaceratingCurio = MODIFIERS.register("lacerating_curio", LaceratingCurioModifier::new);
        MagneticCurio = MODIFIERS.register("magnetic_curio", MagneticCurioModifier::new);
        LightWeightCurio = MODIFIERS.register("light_weight_curio", LightWeightCurioModifier::new);
        WorldBottom = MODIFIERS.register("world_bottom", WorldBottomModifier::new);
        HighFrequencyBarrier = MODIFIERS.register("high_frequency_barrier", HighFrequencyBarrierModifier::new);
        BladeConvergence = MODIFIERS.register("blade_convergence", BladeConvergenceModifier::new);
        Torturing =MODIFIERS.register("torturing", TorturingModifier::new);
        Crystalline = MODIFIERS.register("crystalline", CrystallineModifier::new);
        CrystallineArmor = MODIFIERS.register("crystalline_armor", CrystallineArmorModifier::new);
        ReapersBlessing = MODIFIERS.register("reapers_blessing", ReapersBlessingModifier::new);
        BedrockBreaker = MODIFIERS.register("bedrock_breaker", BedrockBreakerModifier::new);
        BatteryCell = MODIFIERS.register("battery_cell", BatteryCell::new);
        Thunder = MODIFIERS.register("thunder", ThunderModifier::new);
        FieryFire = MODIFIERS.register("fiery_fire", FieryFireModifier::new);
        Frozen = MODIFIERS.register("frozen", FrozenModifier::new);
        FireImmunity = MODIFIERS.register("fire_immunity", FireImmunityModifier::new);
        IceImmunity = MODIFIERS.register("ice_immunity", IceImmunityModifier::new);
        LightningImmunity = MODIFIERS.register("lightning_immunity", LightningImmunityModifier::new);
        ChainLightning = MODIFIERS.register("chain_lightning", ChainLightningModifier::new);
        DragonSoul = MODIFIERS.register("dragon_soul", DragonSoulModifier::new);
        SoulDevourer = MODIFIERS.register("soul_devourer", SoulDevourerModifier::new);
        Shielding = MODIFIERS.register("shielding", ShieldingModifier::new);
        SteadyCurio = MODIFIERS.register("steady_curio", SteadyCurioModifier::new);
        InsatiableCurio = MODIFIERS.register("insatiable_curio", InsatiableCurioModifier::new);
    }

    public STModifiers() {
    }
}
